#spring:
#  kafka:
#    bootstrap-servers: "localhost:9092"
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    prometheus.enabled: true
    refresh.enabled: true
    env.enabled: true
    bus-refresh.enabled: true
    loggers.enabled: true
