version: '3'
services:

  zookeeper:
    container_name: spring-zookeeper
    image: eventuateio/eventuate-zookeeper:latest
    networks:
      - zookeeper-net
    ports:
      - 2182:2181
      - 2889:2888
      - 3889:3888

networks:
  zookeeper-net:
